name = "prateesh-chatbot"
main = "worker.js"
compatibility_date = "2025-04-29"
account_id = "d22786616b3f0f55cf40ceca134e2bcb"

[env.production]
workers_dev = true

[env.staging]
workers_dev = true
route = ""  # Use the workers.dev subdomain